version: '3.4'

services:
  api:
    image: ${DOCKER_REGISTRY-}api
    env_file: .env
    build:
      context: .
      dockerfile: src/API/Dockerfile
    ports:
      - 5000:80
      - 5002:443
#if (SQLServer)
  sql-server-db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    ports:
      - 1433:1433
    environment:
      SA_PASSWORD: "Password1!"
      ACCEPT_EULA: "Y"
    volumes:
      - ./src/Infrastructure/Persistence/VolumeData:/var/opt/data
#endif
#if (PostgreSQL)
  postgres-db:
    image: postgres
    environment:
      POSTGRES_DB: "DatabaseName"
      POSTGRES_USER: "user"
      POSTGRES_PASSWORD: "password"
    ports:
      - 5432:5432
    volumes:
      - ./src/Infrastructure/Persistence/VolumeData:/var/lib/postgresql/data
#endif
  seq:
    image: datalust/seq:latest
    environment:
      - ACCEPT_EULA=Y
    ports:
      - 8081:80

volumes:
    pgdata: