version: '3.4'

services:
  api:
    image: ${DOCKER_REGISTRY-}api
    env_file: .env
    build:
      context: .
      dockerfile: src/API/Dockerfile
    ports:
      - 5000:80
      - 5001:443
#if (SQLServer)
  sql-server-db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    ports:
      - ${Database__Port}:1433
    environment:
      SA_PASSWORD: ${Database__Password}
      ACCEPT_EULA: "Y"
    volumes:
      - ./src/Infrastructure/Persistence/VolumeData:/var/opt/data
#endif
#if (PostgreSQL)
  postgres-db:
    image: postgres
    environment:
      POSTGRES_DB: ${Database__DbName}
      POSTGRES_USER: ${Database__User}
      POSTGRES_PASSWORD: ${Database__Password}
    ports:
      - ${Database__Port}:5432
    volumes:
      - pgdata:/var/lib/postgresql/data
#endif
  seq:
    image: datalust/seq:latest
    environment:
      - ACCEPT_EULA=Y
    ports:
      - 8081:80
      
#if (PostgreSQL)
volumes:
    pgdata:
#endif